import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Auth Layout",
  description: "Generated by create next app"
};


export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h2 style={{ color: "red" }}>Auth Layout</h2>
        {children}
        <br />
        <br />
        <Link href="/">Return Home</Link>

      </body>
    </html>
  );
}
