import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Practice App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navLink = [
    { name: "Home", href: "/" },
    { name: "Login", href: "/login" },
    { name: "Register", href: "/register" },
    { name: "OptionalCatchAll", href: "/optional-catch-all/any" },
    { name: "Blogs", href: "/blogs" },
    { name: "Products", href: "/products" },
  ]

  return (
    <html lang="en">
      <body>
        <h2 style={{ color: "red" }}>Main Layout</h2>
        <div>
          <ul>
            {navLink.map(({ name, href }) => {
              return (<li key={name}><Link href={href}>{name}</Link></li>)
            })}
          </ul>
        </div>
        {children}
        <br />
        <br />
        <Link href="/">Return Home</Link>

      </body>
    </html>
  );
}
