import type { Metadata } from "next";

import type {propsType} from "./products/[productId]/page";

// export const metadata: Metadata = {
//   title: {
//     default: "Practice App",
//     template: "%s",
//   },
//   description: "Generated by create next app",
// };

export const generateMetadata = async ({params} : propsType): Promise<Metadata> => {
  console.log("params:", (await params))
  return {
    title: {
      default: "Practice App",
      template: "%s",
    },
    description: "Practice related pages",
  };
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h2 style={{ color: "red" }}>Main Layout</h2>
        {children}
      </body>
    </html>
  );
}
