import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Practice App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navLink = [
    { name: "Home", href: "/" },
    { name: "Login", href: "/login" },
    { name: "Register", href: "/register" },
    { name: "OptionalCatchAll", href: "/optional-catch-all/any" },
    { name: "Blogs", href: "/blogs/something" },
    { name: "Products", href: "/products" },
    { name: "Dashboard", href: "/dashboard" },
    { name: "f3", href: "/f3" },
  ]

  return (
    <html lang="en">
      <body>

        <div>
          <div className="header text-red-50"> header </div>
          <div className="main"> main </div>
          <div className="footer"> footer </div>

        </div>



        <div style={{ background: "rgba(245, 255, 131, 1)" }}>
          <h2 style={{ color: "red" }}>Main Layout</h2>
          <div>
            <ul>
              {navLink.map(({ name, href }) => {
                return (<li key={name}><Link href={href}>{name}</Link></li>)
              })}
            </ul>
          </div>
        </div>
        {children}
        <br />
        <br />
        <Link href="/">Return Home</Link>

      </body>
    </html>
  );
}
